.TH CHAOSVPN 5 "Feburary 2010" "Discordian coreutils" ""
.SH NAME
chaosvpn.conf - configuration file for chaosvpn
.SH DESCRIPTION
.B chaosvpn.conf
configures the behavior of the config generator.
.PP
This config file is written in a perl-like syntax. The reason for that
was chaosvpn 1.0, which was written in perl.
.SH CONFIG
.B $my_peerid
.RS 4
.PP
This is your network name - it has to be unique in the master configuration.
.PP
.RE
.B $my_vpn_ip
.RS 4
.PP
Your IPv4 address within the network.
.PP
.RE
.B $my_vpn_netmask
.RS 4
.PP
The netmask for your IPv4 address. If you only use one IP address in
your network, or route the rest of your IP addresses to other devices
use "255.255.255.255" - in 99% of all usages you should keep this at
"255.255.255.255".
.PP
.RE
.B $my_vpn_ip6
.RS 4
.PP
Your IPv6 address of the VPN interface on your node/gateway. If you do
not use IPv6, leave this field empty.
.PP
.RE
.B $my_ip
.RS 4
.PP
The public IP address on which the tincd daemon will listen. Leave this empty to listen on all
interfaces (0.0.0.0). Make sure that you open the necessary ports on an existing firewall.
.PP
.RE
.B @exclude
.RS 4
.PP
The exclude parameter can contain a list of node names. A VPN connection
will not established to them. You may want to use it if you have another
VPN, or direct connection to these nodes.
.PP
.RE
.B $networkname
.RS 4
.PP
Name of you config in tinc. For CCC ChaosVPN set this to "chaos".
.PP
.RE
.B $tincd_bin
(optional)
.RS 4
.PP
Path to tincd executable. Default is "/usr/sbin/tincd".
.PP
.RE
.B $routemetric
.RS 4
.PP
Metric of all routes through the ChaosVPN interface. Only needed if you
wanna build up redudant routes. Keep this at "0" unless you know why
you change it.
.PP
.RE
.B $routeadd
.br
.B $routeadd6
.RS 4
.PP
Command to setup the network routes. These may be different on other operating systems.
.PP
.RE
.B $ifconfig
.br
.B $ifconfig6
.RS 4
.PP
Command to setup IP address and netmask for IPv4 and IPv6. This may be different
on other operating systems too.
.PP
.RE
.B $master_url
.RS 4
.PP
URL to get the master configuration file. Default is configured to CCC ChaosVPN.
.PP
.RE
.B $masterdata_signkey
(optional)
.RS 4
.PP
Public Key to verify data from master URL. If no key is defined, it will fall back to
cleartext transport - this will not work for CCC ChaosVPN.
.PP
.RE
.B $base
.RS 4
.PP
Location of the generated tinc configuration.
.PP
.RE
.B $pidfile
.RS 4
.PP
Location of the ProcessID file to ensure tincd process is running only once.
.PP
.RE
.B $tincd_debuglevel
(optional)
.RS 4
.PP
Debuglevel of the tincd output. More details in tincd documentation.
.PP
.RE
.B $tincd_restart_delay
(optional)
.RS 4
.PP
Number of seconds to wait before tincd is restarted after it has
unexpectedly terminated.
.PP
.RE
.B $update_interval
(optional)
.RS 4
.PP
Number of seconds to wait between refetching the remote config.
.PP
.SH SEE ALSO
chaosvpn(5)
